In [ ]:
# Program 1:Calculate total weekly energy from a list
daily_KWH = [400, 850, 400, 350, 500, 600]
total_energy = sum(daily_KWH)
print("Total Energy Used:",total_energy, " KWH")

Total Energy Used: 3100  KWH

In [ ]:
# Program 2: store building usage data
building_usage = {
    "CSE": 400,
    "Hostel": 850
}
print("Hostel used:",building_usage["Hostel"], "KWH")

Hostel used: 850 KWH

In [ ]:
# Program 3: function to calculate electricity cost
def calculate_bill(KWH, rate_per_unit):
  return KWH * rate_per_unit

todays_bill = calculate_bill(400,8)
print("Today's estimated bill is Rs.", todays_bill)

Today's estimated bill is Rs. 3200

In [ ]:
# Program 4: Read a file line by line
with open("campus_energy.csv", "r") as file:
  for line in file.readlines():
    print(line.strip())

Date,Building,KWH_Used,Peak_Hour_Usage
,CSE,400,120
,HOSTEL,850,250
,CSE,400,110
,ECE,350,325
,CIVIL,500,210
,HOSTEL,600,111

In [ ]:
# Import the pandas library
import pandas as pd

# Load the dataset you created
df = pd.read_csv('campus_energy.csv')

# Display the first few rows of the data
print("Here is the raw data:")
display(df.head())

# Group the data to see total usage per building
building_totals = df.groupby('Building')['KWH_Used'].sum()
print("\nTotal usage per building:")
print(building_totals)

#Generate a statistical summary(average, min, max) of the numeric columns
print("\nStatistical Summary:")
display(df.describe())

Here is the raw data:

   Date Building  KWH_Used  Peak_Hour_Usage
0   NaN      CSE       400              120
1   NaN   HOSTEL       850              250
2   NaN      CSE       400              110
3   NaN      ECE       350              325
4   NaN    CIVIL       500              210

Total usage per building:
Building
CIVIL      500
CSE        800
ECE        350
HOSTEL    1450
Name: KWH_Used, dtype: int64

Statistical Summary:

       Date    KWH_Used  Peak_Hour_Usage
count   0.0    6.000000         6.000000
mean    NaN  516.666667       187.666667
std     NaN  186.189867        89.144078
min     NaN  350.000000       110.000000
25%     NaN  400.000000       113.250000
50%     NaN  450.000000       165.000000
75%     NaN  575.000000       240.000000
max     NaN  850.000000       325.000000

In [ ]:
# Create the README.md file and write a message inside it
with open("README.md", "w") as file:
  file.write("# Smart Campus Energy Project\n")
  file.write("This repository contains my Week 1 hands-on Python and pandas assignments.\n")
  file.write("Created by: [SHALINI PARVATHANENI]")

print("README.md has been successfully created!")

README.md has been successfully created!